#!/usr/bin/env python3
"""
PostToolUseFailure Logger Hook

Fires when any tool call fails (Bash, Edit, Write, etc.).
Logs failures to work/errors.md for post-session debugging.
Always exits 0 — notification only, cannot block.

Creates a persistent "black box" error log that survives compaction.
Agents and humans can review it to understand what went wrong.
"""

import json
import sys
from datetime import datetime
from pathlib import Path


def main():
    # Hook profile gate
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from hook_base import should_run
        if not should_run("tool-failure-logger"):
            sys.exit(0)
    except ImportError:
        pass

    try:
        raw = sys.stdin.read()
        if not raw.strip():
            sys.exit(0)

        data = json.loads(raw)
        cwd = Path(data.get("cwd", ".")).resolve()

        # Vaultguard: only run in project directories with CLAUDE.md
        if not (cwd / "CLAUDE.md").exists():
            sys.exit(0)

        tool_name = data.get("tool_name", "unknown")
        error = data.get("error", "no error details")
        tool_input = data.get("tool_input", {})
        is_interrupt = data.get("is_interrupt", False)

        # Skip user interrupts — not real errors
        if is_interrupt:
            sys.exit(0)

        # Extract useful context from tool_input
        context = ""
        if tool_name == "Bash":
            context = tool_input.get("command", "")[:200]
        elif tool_name == "Edit":
            context = tool_input.get("file_path", "")
        elif tool_name == "Write":
            context = tool_input.get("file_path", "")
        elif tool_name == "Read":
            context = tool_input.get("file_path", "")
        elif tool_name.startswith("mcp__"):
            # MCP tool — log the full tool name
            context = json.dumps(tool_input, ensure_ascii=False)[:200]
        else:
            context = json.dumps(tool_input, ensure_ascii=False)[:150]

        # Truncate error message
        error_short = error[:300].replace("\n", " ").strip()

        # Log to work/errors.md
        work_dir = cwd / "work"
        work_dir.mkdir(parents=True, exist_ok=True)
        log_file = work_dir / "errors.md"

        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        if not log_file.exists():
            header = "# Tool Failure Log\n\n"
            header += "> Auto-generated by PostToolUseFailure hook.\n"
            header += "> Review after session to understand what went wrong.\n\n"
            log_file.write_text(header, encoding="utf-8")

        entry = f"### {now} — {tool_name}\n"
        if context:
            entry += f"**Context:** `{context}`\n"
        entry += f"**Error:** {error_short}\n\n"

        with open(log_file, "a", encoding="utf-8") as f:
            f.write(entry)

    except Exception as e:
        # Never crash — just log to stderr and exit
        print(f"[tool-failure-logger] Error: {e}", file=sys.stderr)

    sys.exit(0)


if __name__ == "__main__":
    main()
